#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QRit1._1.Resource", IsApplication=true)]

namespace QRit1._1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::QRit1._1.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::QRit1._1.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::QRit1._1.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int butto1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int button3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int button4 = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int buttonZxingFlash = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int contentFrame = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int linearLayout1 = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int linearLayout2 = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int textView1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int textView2 = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int textView3 = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int textViewScan = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ZxingOverlay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int zxingscanneractivitylayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int zxingscannerfragmentlayout = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
